name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npx cap sync ios

      - name: Install CocoaPods
        run: pod install --project-directory=ios/App || echo "CocoaPods not initialized yet"

      - name: Build iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release
