name: Build iOS App with Firebase

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npx cap sync ios

      # Firebase secrets (optional)
      # - name: Restore google-services.json
      #   run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json

      # - name: Restore GoogleService-Info.plist
      #   run: echo "${{ secrets.GOOGLESERVICE_INFO_PLIST }}" | base64 -d > ios/App/GoogleService-Info.plist

      - name: CocoaPods install
        run: pod install --project-directory=ios/App || echo "Pods not initialized"

      - name: Build iOS App
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release
